//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientDemographicsDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        public decimal Patient_ID { get; set; }
        public string Patient_Details { get; set; }
    }
}
